### ISSUE TITLE
403. That's an error

### ISSUE THREAD

**Issue by khuong291** [google/gtm-oauth2#87] opened 2016-12-01 04:58 UTC

**Comment by khuong291** [comment] 2016-12-01 04:59
This user-agent is not permitted to make an OAuth authorization request to Google as It is classified as an embedded user-agent...

**Comment by thomasvl** [comment] 2016-12-01 13:17
Please see the [deprecation notice](https://github.com/google/gtm-oauth2#warning-deprecation-notice)

Duplicate of #84 & #85

**Closed by thomasvl** 2016-12-01 13:17 UTC

**Comment by khuong291** [comment] 2016-12-01 14:09
Hi @thomasvl , so I should use https://github.com/google/GTMAppAuth instead?

**Comment by thomasvl** [comment] 2016-12-01 14:17
Yup

**Comment by khuong291** [comment] 2016-12-02 02:01
Thank you :dancing_men:
